version: "3.9"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
  grafana:
    image: grafana/grafana
    restart: always
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 80:3000
    depends_on:
      - prometheus
    links:
      - prometheus
    networks:
      - monitoring
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  app:
    build:
      context: .
    volumes:
      - ./:/app
    ports: 
      - 3001:3001
    networks:
      - monitoring
    depends_on:
      - prometheus
networks:
  monitoring:
    driver: bridge